#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql --regex-ruby="/^[ \t]*scope[ \t]*:([a-zA-Z0-9_]+)/\1/"
mv "$dir/$$.tags" "$dir/tags"
